services:
  db:
    container_name: django_api_db
    build:
      context: .
      dockerfile: DockerfilePsql
    volumes:
      - psqldata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRE_DB}
      - POSTGRES_USER=${POSTGRE_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PW}

  web:
    container_name: django_web_api
    build:
      context: .
      dockerfile: DockerfilePython
    volumes:
      - ./api:/api
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db

volumes:
  psqldata: